In [6]:
from data_process import *
#from models import *
#from utility import *
#from train_evaluate import *
import pandas as pd
import os
from tqdm import tqdm

In [2]:
#CHANGE THE SKIP TOKEN

#st = sequence
#lst = 
#a = next token
#user_id = user
#skip = skip
#buy = was the next a hit
#display(pd.read_csv('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/transition_store_test.csv'))

,st,lst,a,buy,user_id,skip
0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,151,1,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,"[0, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1,150,1,0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,"[0, 151, 150, 0, 0, 0, 0, 0, 0, 0, 0]",2,149,1,0,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
3,"[0, 151, 150, 149, 0, 0, 0, 0, 0, 0, 0]",3,148,1,0,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
4,"[0, 151, 150, 149, 148, 0, 0, 0, 0, 0, 0]",4,147,1,0,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...
19314,"[5, 21195, 21194, 0, 0, 0, 0, 0, 0, 0, 0]",2,21193,1,5,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]"
19315,"[5, 21195, 21194, 21193, 0, 0, 0, 0, 0, 0, 0]",3,21192,1,5,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]"
19316,"[5, 21195, 21194, 21193, 21192, 0, 0, 0, 0, 0, 0]",4,21191,1,5,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]"
19317,"[5, 21195, 21194, 21193, 21192, 21191, 0, 0, 0...",5,21190,1,5,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]"
19318,"[5, 21195, 21194, 21193, 21192, 21191, 21190, ...",6,21189,1,5,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]"

In [ ]:
m = DataModule('/home/pseshadri/sequential-recommendation/sequential-music-recommendation/datasets/transition_store/', 32)

In [2]:
filepath = '/mnt/data2/pavans/pavans/training_set'
test_file = os.listdir(filepath)[1]

df = pd.read_csv(os.path.join(filepath, test_file))
df

,session_id,session_position,session_length,track_id_clean,skip_1,skip_2,skip_3,not_skipped,context_switch,no_pause_before_play,...,long_pause_before_play,hist_user_behavior_n_seekfwd,hist_user_behavior_n_seekback,hist_user_behavior_is_shuffle,hour_of_day,date,premium,context_type,hist_user_behavior_reason_start,hist_user_behavior_reason_end
0,10_0000172c-a619-44a1-9284-6f88ba876507,1,20,t_10a02b6d-bd97-40e0-907a-b964f0e8c3e7,False,True,True,False,0,0,...,0,0,0,False,20,2018-07-24,False,user_collection,trackdone,fwdbtn
1,10_0000172c-a619-44a1-9284-6f88ba876507,2,20,t_79c5d73d-9949-4a25-a98e-9839a616d400,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
2,10_0000172c-a619-44a1-9284-6f88ba876507,3,20,t_612e16f4-14e2-4e4c-9b97-14ab82240a47,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
3,10_0000172c-a619-44a1-9284-6f88ba876507,4,20,t_cd661951-833f-4392-b101-f83568a0ae70,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,fwdbtn
4,10_0000172c-a619-44a1-9284-6f88ba876507,5,20,t_8f9f2397-334b-48ee-9120-96d9ddf32f92,True,True,True,False,0,1,...,0,0,0,False,20,2018-07-24,False,user_collection,fwdbtn,backbtn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257778,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,16,20,t_363c666e-73aa-4b97-8c65-667cd0e190a0,False,False,False,True,0,1,...,0,0,1,False,11,2018-07-25,True,catalog,fwdbtn,trackdone
3257779,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,17,20,t_e6dbaa5a-419a-4b45-a1c1-09867a88f4ec,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257780,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,18,20,t_eacd7e86-70a8-4207-a412-238cc55c1112,False,False,False,True,0,1,...,0,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257781,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,19,20,t_2a55e695-7894-42aa-b920-52d1cbaf164c,False,False,False,True,0,0,...,1,0,0,False,11,2018-07-25,True,catalog,trackdone,trackdone
3257782,10_ffffeb79-f76f-4c82-bf04-b7a7ae108a98,20,20,t_a66ea088-b357-449a-8a1e-64dd0b8d6cb5,False,False,True,False,0,0,...,1,0,0,False,11,2018-07-25,True,catalog,trackdone,endplay

In [ ]:
sessions = list()
skips = list()
vocab = set()
session_ids = list()
cols = ['session_position', 'track_id_clean', 'skip_level'] #+ ['skip_1', 'skip_2', 'skip_3']
#skip_level = lambda df_: [4 - x for x in range(1, 4) if df_[f'skip_{x}'].bool() else 0] #0 - 3 in order of most severe skip
for s, df_s in tqdm(df.groupby(['session_id'])):
    df_s.sort_values(by = ['session_position'], axis=0, inplace=True)
    df_s['skip_level'] = ((df_s['skip_1'].astype(int) + df_s['skip_2'].astype(int) + df_s['skip_3'].astype(int)))
    df_s = df_s[cols]
    sessions.append(df_s['track_id_clean'].to_list())
    skips.append(df_s['skip_level'])
    vocab = vocab.union(set(sessions[-1]))
    session_ids.append(s)
print(len(session_ids) == len(sessions))

 20%|██        | 39779/195829 [02:51<18:27, 140.86it/s]

In [21]:
print( 3 % 4)

3

In [1]:
import torch

In [9]:
x = torch.linspace(0,21, 20).long()
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 21])

In [12]:
print(torch.unique(x, return_inverse=True)[1])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [23]:
y = torch.randint(67, (128,20))

In [32]:
print(torch.unique(y, return_inverse=True)[1])

tensor([[22, 17, 50,  ..., 43,  7,  2],
        [45, 24,  4,  ..., 50, 44,  8],
        [51, 59, 21,  ..., 36,  0,  7],
        ...,
        [44, 65, 26,  ..., 23, 26, 19],
        [23, 45, 12,  ...,  4, 22,  7],
        [58,  2, 36,  ..., 24,  7, 30]])

In [233]:
import torch 
PADDING_ITEM = 0
mask_token = 2
def _mask_tracks(X, prop=0.15):
        Y = X[X != PADDING_ITEM]
        indices = torch.randperm(torch.numel(Y))
        indices = indices[:int(0.15//(1/indices.shape[0]))]
        Y[indices] = mask_token

        X[X != PADDING_ITEM] = Y

        return X

def _mask_tracks2(X, prop=0.15):
        X = X.detach().clone()
        dist = torch.ones(X.shape)
        dist[X == PADDING_ITEM] = 0
        #indices = torch.clamp(torch.multinomial(dist, int(X.shape[1] // (1/prop))), min=torch.ones((X.shape[0], 1)), 
                              #max=(torch.argmin(X, dim=1) - 1).unsqueeze(dim=-1)).long()
        indices = torch.multinomial(dist, 2)
        
        batch_idx = torch.tile(torch.linspace(0, X.shape[0] - 1, steps = X.shape[0]), (indices.shape[1],1)).long().T

        X[batch_idx, indices] = mask_token

        last_item = torch.argmin(X, dim=1)
        X[range(X.shape[0]), last_item] = mask_token

        return X

In [236]:
y = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
z = torch.cat((torch.randint(300000, (64, 15)), torch.zeros((64, 6))), axis = 1)
m = _mask_tracks2(y)
#print(m)
#print(torch.argwhere(m == 2))
masked_targets = y[m == mask_token].view(64, 3)
print(masked_targets.shape)
last_item = torch.argmin(y, dim=1) - 1
#print(y[range(y.shape[0]), last_item])
masked_targets[:, -1] = z[range(z.shape[0]), last_item]

print(m)
print(masked_targets)

torch.Size([64, 3])
tensor([[1.3867e+05, 4.7810e+04, 1.1316e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9929e+05, 1.6205e+05, 5.1511e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.9202e+05, 2.3774e+05, 2.8134e+05,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [7.6040e+04, 1.9671e+05, 2.5400e+02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.6113e+05, 1.8642e+05, 2.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.7354e+05, 2.0000e+00, 3.3003e+04,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])
tensor([[256447.,   4439., 287229.],
        [ 95003., 137267., 195677.],
        [113269., 198033.,  71481.],
        [237428.,  48155., 115184.],
        [ 86473., 104540., 210444.],
        [171052.,  68637.,  79306.],
        [123518., 211093., 189224.],
        [182003., 209677., 145793.],
        [200162., 133951., 264391.],
        [121833.,  96787., 124801.],
        [254808., 288213., 149961.],
        [161539., 212979.,  82874.],
        [ 11578., 276399.,  21897.],
        [192485., 126383., 151897.],
        [166405., 126737.,  26277.],
        [ 25276., 218922.,  73480.],
        [111447., 103793., 100654.],
        [237780., 237111., 292001.],
        [183643., 262255.,  83480.],
        [113794.,  84094., 186086.],
        [277806., 196198.,  95938.],
        [  7489., 296597., 170578.],
        [ 53345., 213778.,  87165.],
        [230353., 254010., 235826.],
        [165183., 141512., 130804.],
        [237274., 162605.,  75553.],
        [126236.,  62297., 148376.],
        [275445., 118067., 234967.],
        [181650.,  84649., 229630.],
        [220785., 155771., 154277.],
        [248369.,   9247., 126698.],
        [175951., 177505., 167556.],
        [129472., 126479.,  19213.],
        [ 43055.,  60533.,   1806.],
        [134627., 284831., 249591.],
        [ 38492., 119543.,  76444.],
        [168111., 129098.,  48119.],
        [276172.,  75948., 122120.],
        [168940.,  60103., 171989.],
        [291986., 195198., 148059.],
        [110756., 225997., 108601.],
        [298261., 195162., 213217.],
        [168483., 155349., 230966.],
        [267470., 167855., 289358.],
        [ 65662.,  44271., 243328.],
        [171630., 207601., 244986.],
        [100430., 122958.,  77163.],
        [ 86540., 171469., 196556.],
        [185662., 118152., 296011.],
        [210302., 165084., 211579.],
        [223598., 227525.,  24199.],
        [ 74842., 133471., 276110.],
        [102803., 278730., 213925.],
        [103473., 247223.,  88989.],
        [272286., 144066.,  16761.],
        [ 53976., 295815., 244358.],
        [ 17010., 153321., 149194.],
        [174386.,   5365., 160563.],
        [213120., 114629.,  67870.],
        [131924., 118682., 293198.],
        [111325., 189317., 291680.],
        [191437., 216573., 282547.],
        [ 16464.,  84156., 279572.],
        [ 44189., 125564.,  65958.]])

In [229]:
print(int((21 - 3) // (1/0.15)))

2

In [1]:
import pandas as pd

df = pd.read_csv('/home/pavans/dev/sequential-music-recommendation/datasets/lfm/plays_with_session_with_skip_2.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,Fuck Me Im Famous (Pacha Ibiza)-09-28-2007,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Composition 0919 (Live_2009_4_15),1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc2 (Live_2009_4_15),1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Hibari (Live_2009_4_15),1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc1 (Live_2009_4_15),1,1

In [4]:
df['track-name'] = df['track-name'].factorize()[0]
df.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,0,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,1,1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,2,1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,3,1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,4,1,1

In [7]:
groups = df.groupby('Session_id')
groups.head()

,Unnamed: 0.1,Unnamed: 0,user,timestamp,artist_id,artist_name,track_id,track-name,Session_id,skip
0,0,0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,0,0,1
1,1,1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,1,1,1
2,2,2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,2,1,1
3,3,3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,3,1,1
4,4,4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,4,1,1
...,...,...,...,...,...,...,...,...,...,...
19150842,19150842,19150842,user_001000,2008-01-27 23:26:56+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,936b1924-be61-40c8-85b1-a0ddd03c47b6,83486,1042297,1
19150843,19150843,19150843,user_001000,2008-01-27 23:23:26+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,3536ef47-dcdd-4a9b-980f-5febcb655fc9,10039,1042297,1
19150844,19150844,19150844,user_001000,2008-01-27 23:16:30+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,e3820060-90e7-4359-8243-bf32cc6904e7,63929,1042297,1
19150845,19150845,19150845,user_001000,2008-01-27 23:13:33+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,be2d253d-2b90-4703-b20a-6ca9531e251f,153924,1042297,1
19150846,19150846,19150846,user_001000,2008-01-27 23:09:37+00:00,9e53f84d-ef44-4c16-9677-5fd4d78cbd7d,Wilco,747bb717-fa09-4dc9-aa78-8c13e2c8e53f,82130,1042297,1

In [11]:
sessions = groups['track-name'].apply(list)
skips = groups['skip'].apply(list)
vocab = set(df['track-name'].to_list())
print(len([s for s in sessions if len(s) > 5]))

642539

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/pavans/dev/sequential-music-recommendation/datasets/lfm-2b/plays_with_session_with_skip2.csv')

In [5]:
df
df['track-name'] = df['track-name'].factorize()[0]

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
0,0,1000,4154409,14720156,2020-01-01 21:02:17,0,False
1,1,1000,42521726,14720156,2020-01-01 21:03:37,0,False
2,2,1000,22978395,14720156,2020-01-01 21:07:49,0,False
3,3,1000,42103242,14720156,2020-01-01 21:13:37,0,False
4,4,1000,25123379,14720156,2020-01-01 21:15:06,0,False
...,...,...,...,...,...,...,...
30357781,30357781,9998,8302820,19987164,2020-03-20 12:10:24,2223213,False
30357782,30357782,9998,21928646,19987164,2020-03-20 12:15:26,2223213,False
30357783,30357783,9998,37491098,19987164,2020-03-20 12:20:56,2223213,False
30357784,30357784,9998,17792531,19987164,2020-03-20 12:25:16,2223213,False
30357785,30357785,9998,15348690,19987164,2020-03-20 12:36:22,2223213,False

In [21]:

display(df[df['track-name'] == 682330].sort_values(by='Session_id'))
display(df[df['track-name'] == 278671])
display(df[df['Session_id'] == 171390])

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
2313656,2313656,119957,682330,9370923,2020-02-10 10:06:43,171359,False
2313914,2313914,119957,682330,9370923,2020-02-16 20:45:45,171385,False
2313933,2313933,119957,682330,9370923,2020-02-17 09:37:39,171387,False
2313966,2313966,119957,682330,9370923,2020-02-17 15:13:20,171389,False
2313974,2313974,119957,682330,9370923,2020-02-17 18:42:12,171390,False
2314181,2314181,119957,682330,9370923,2020-02-19 18:17:20,171403,False
2314228,2314228,119957,682330,9370923,2020-02-19 21:16:52,171404,False
2314236,2314236,119957,682330,9370923,2020-02-19 21:43:34,171404,False
2314260,2314260,119957,682330,9370923,2020-02-20 08:46:26,171405,False
2314285,2314285,119957,682330,9370923,2020-02-21 10:06:40,171410,False
2314314,2314314,119957,682330,9370923,2020-02-22 12:22:48,171413,False
2314324,2314324,119957,682330,9370923,2020-02-22 12:56:04,171413,False
2314354,2314354,119957,682330,9370923,2020-02-23 16:49:55,171416,False
2314397,2314397,119957,682330,9370923,2020-02-23 19:48:45,171416,False
2314544,2314544,119957,682330,9370923,2020-02-24 21:33:59,171423,False
2314779,2314779,119957,682330,9370923,2020-02-27 18:49:58,171448,False
2314847,2314847,119957,682330,9370923,2020-02-28 11:45:50,171450,False
2314883,2314883,119957,682330,9370923,2020-02-29 13:31:34,171452,False
2314927,2314927,119957,682330,9370923,2020-03-01 13:51:20,171456,False
2315106,2315106,119957,682330,9370923,2020-03-06 00:47:00,171466,False
2315160,2315160,119957,682330,9370923,2020-03-06 15:27:54,171468,True
2315187,2315187,119957,682330,9370923,2020-03-06 17:30:45,171469,False
2315248,2315248,119957,682330,9370923,2020-03-07 00:17:15,171472,False
2315429,2315429,119957,682330,9370923,2020-03-09 10:15:33,171487,False
2315544,2315544,119957,682330,9370923,2020-03-10 12:12:38,171492,False
2315552,2315552,119957,682330,9370923,2020-03-10 14:42:36,171493,False
2315749,2315749,119957,682330,9370923,2020-03-12 10:59:27,171505,False
2315750,2315750,119957,682330,9370923,2020-03-12 11:20:13,171506,False
3879802,3879802,14413,682330,9370923,2020-03-02 11:01:04,286553,False
3879834,3879834,14413,682330,9370923,2020-03-02 17:57:20,286554,False
3879963,3879963,14413,682330,9370923,2020-03-04 10:56:30,286560,False

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
733575,733575,10539,278671,20555841,2020-03-13 03:58:08,49439,False
734103,734103,10539,278671,20555841,2020-03-19 15:25:41,49458,False

,Unnamed: 0,user,track-name,album_id,timestamp,Session_id,skip
2313974,2313974,119957,682330,9370923,2020-02-17 18:42:12,171390,False
2313975,2313975,119957,682346,18052563,2020-02-17 18:48:31,171390,False
2313976,2313976,119957,682347,17615673,2020-02-17 18:52:39,171390,False
2313977,2313977,119957,682348,16151311,2020-02-17 18:56:57,171390,False
2313978,2313978,119957,35302,22608282,2020-02-17 18:59:58,171390,False
2313979,2313979,119957,682349,22163350,2020-02-17 19:05:27,171390,False

In [28]:
cols = df.columns
for x in cols:
    df[x] = df[x].apply(type)
    print(df[x].unique())

[<class 'int'>]
[<class 'int'>]
[<class 'int'>]
[<class 'int'>]
[<class 'str'>]
[<class 'int'>]
[<class 'bool'>]

In [29]:
df.apply(type)

Unnamed: 0    <class 'pandas.core.series.Series'>
user          <class 'pandas.core.series.Series'>
track-name    <class 'pandas.core.series.Series'>
album_id      <class 'pandas.core.series.Series'>
timestamp     <class 'pandas.core.series.Series'>
Session_id    <class 'pandas.core.series.Series'>
skip          <class 'pandas.core.series.Series'>
dtype: object

In [7]:
import yaml

with open('config/config-lfm2B.yml', 'r') as file:
        config = yaml.safe_load(file)

In [8]:
data = LfMDataModule(config['data_params']['data_path'], config['data_params']['batch_size'], dev=config['dev'])

vocab: 1500866 sessions:464810 interactions: 7624976

In [9]:
from models import VanillaTransformer
model = VanillaTransformer(**config['model_params'], vocab_size=len(data.vocab)).to('cuda')
model.eval()
torch.cuda.empty_cache()
from tqdm import tqdm
with torch.no_grad():
    for batch in tqdm(data.test_dataloader()):
        batch = tuple([x.cuda() for x in batch])
        '''
        sessions, targets, skip = batch
        skip = skip.long()
        targets = targets.long()
        sessions = model._mask_tracks(sessions, TRAIN=False)
        output_1, x_ = model(sessions)
        output, targets = model.sampled_softmax(output_1, targets)
        output = output.transpose(1, 2)
        target_loss = model.loss(output, targets)
        if torch.isnan(target_loss).any():
            print(output_1, output, targets, skip)
        '''
        loss = model.test_step(batch, 0)
        if torch.isnan(loss).any():
            print(batch)

  0%|                                                                                                                                                                                                                                                                                                          | 0/3632 [00:00<?, ?it/s]/home/pavans/miniconda3/envs/rec/lib/python3.9/site-packages/pytorch_lightning/core/module.py:416: UserWarning: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`
  rank_zero_warn(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3632/3632 [02:54<00:00, 20.85it/s]

In [14]:
counter = 0
for batch in tqdm(data.val_dataloader()):
    if counter > 5:
        break
    for b in batch:
        print(b)
    counter+=1

  0%|                                                                                                                                                                                                                                                                                                | 1/3632 [00:03<3:54:04,  3.87s/it]

tensor([[ 768,  769,  770,  ...,    0,    0,    0],
        [ 787,  788,  789,  ...,    0,    0,    0],
        [ 805,  806,  760,  ...,    0,    0,    0],
        ...,
        [9695, 9718, 9853,  ...,    0,    0,    0],
        [9618, 9621, 9619,  ...,    0,    0,    0],
        [9899, 9900, 9842,  ...,    0,    0,    0]], dtype=torch.int32)
tensor([ 393,  803,  820,  833, 1027, 1053, 1059, 1345, 1529, 1545, 1135, 1256,
        1262, 4346, 4602, 4621, 4631, 5116, 5121, 5312, 5338, 5363, 5412, 4382,
        5448, 5467, 5486, 5501, 6064, 6066, 6449, 6289, 6445, 6088, 5973, 6214,
        5649, 6448,  574,  339, 6454, 6440, 6214, 6458,  339, 6088, 5741, 6484,
        6492, 3153, 5610, 6132, 6560, 7106, 7185, 7189, 7272, 7315, 7413, 7452,
        7487, 7501, 7556, 7564, 7391, 7635, 7645, 7433, 7575, 7419, 7704, 7557,
        7331, 7328, 7746, 7782, 7796, 7848, 7868, 7873, 7922, 7900, 7919, 8016,
        7887, 8093, 8113, 8130, 8143, 8159, 8173, 8184, 8191, 8201, 8208, 8229,
        8241, 8298,  375, 3572, 8406, 8438, 8408, 8440, 8445, 5601, 8550, 8569,
        8620, 8697, 8700, 8718, 8738, 9417, 9422, 9068, 9865, 9873, 7201, 9884,
        9913, 9919, 9900,  873, 9715,  873, 9897, 9622], dtype=torch.int32)
tensor([ 785,  394,  821,  834, 1044, 1054, 1344, 1061, 1279, 1546, 1169, 1236,
        1268, 4348, 4603, 4622, 4632, 5117, 5133, 5313, 5339, 5363, 5413, 5430,
        5449, 5468, 5487, 5502, 6065, 6065, 6450, 6459, 6446, 6455, 6444, 6351,
         525, 6449, 6458, 5795, 6359, 6441, 6351, 6289, 5795, 6455, 6474, 6485,
        6493, 6535, 5625, 5462, 6561, 7107, 7185, 7191, 7273, 7316, 7312, 7453,
        7488, 7502, 7456, 7547, 7630, 7636, 7314, 7416, 7312, 7371, 7439, 7344,
        7728, 7732, 7747, 7783, 7797, 7849, 7869, 7874, 7923, 7903, 7905, 8017,
        7888, 8094, 8114, 8131, 8144, 8160, 8174, 6753, 8101, 8202, 8209, 8230,
        8242, 8299, 6191, 8393, 8407, 8439, 8409, 8441, 8446, 8452, 8551, 8562,
        8621, 8698, 8701, 8719, 8739, 9418, 9423, 9195, 9866, 9873, 9860, 9867,
        9914, 9914, 9900, 9616, 9716, 9616, 9898, 9623], dtype=torch.int32)
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)
tensor([[ 9625,  9712,  9713,  ...,     0,     0,     0],
        [ 9900,  9842,  9885,  ...,     0,     0,     0],
        [ 9927,  9919,  9919,  ...,     0,     0,     0],
        ...,
        [13779, 13780, 13781,  ...,     0,     0,     0],
        [13764, 13828, 13726,  ...,     0,     0,     0],
        [13760,  8486, 13657,  ...,     0,     0,     0]], dtype=torch.int32)
tensor([ 9898,  9623,  9919,  9905,  9616,  9933,  8431,  9660,  9797, 10200,
         3708,  9621,  3269, 10248, 10260, 10264, 10308,  9920,  9917,  9931,
         9898,  8180, 10343,  9920, 10352, 10364,  8430,  6017,  9917,  9885,
         8937,  3359, 10568, 10426, 10774, 11189, 11467, 11415, 11389, 11498,
        11460, 11546, 11428, 11891, 13063, 13073, 13082, 13089, 13097, 13107,
        13136, 13142, 13146, 13163,  6361, 13153, 13185, 13195, 13202, 13205,
        13220, 13233, 13241, 13245, 13250, 13253, 13263, 13273, 13278, 13281,
        13285, 13291,  8003,   977, 13248, 13339, 13349,   839, 13361, 13366,
        13373, 13383, 13393, 13399, 13408, 13408, 13419, 13425, 13435, 13442,
        13408, 13445, 13453, 13467, 13478, 13489, 13485, 13499, 13504, 12986,
        13120, 13447, 13520, 13528, 13538, 13541, 13571, 13581, 13591, 13601,
        13609, 13620, 13630, 13637, 13552, 13640, 13646,   951, 13670, 13710,
        13722, 13741, 13688, 13769, 13776, 13783, 13710, 13758],
       dtype=torch.int32)
tensor([ 9895,  9624,  9914,  9902,  9617,  9916,  3434, 10188, 10191, 10201,
        10215, 10227, 10191, 10249, 10261,  9811,  9934,  9917,  9913,  9931,
         9895, 10331, 10344,  9917, 10353, 10365, 10374, 10519,  9913,  9866,
         9715, 10558, 10338,  9380, 10775, 11190, 11468, 11472, 11254, 11499,
        11461, 11547, 11429, 11892, 13064, 13068, 13083,  9352, 13098, 13108,
        13137, 13142, 13147, 13163, 13170, 13154, 13186, 13196, 13203,  8523,
        13221, 13234, 13242, 13246, 13251, 13174, 13263, 13273, 13277, 12981,
        13285, 13292,  8008, 13238, 13249, 13340, 13350, 13357, 13361, 13367,
        13374, 13384, 13394, 13400, 13409, 13409,  2913, 13425, 13436, 13443,
        13409, 13446, 13454, 13322, 13479, 13488, 13485, 13500, 13504, 13310,
        13456, 13484, 13521, 13529, 13539, 13541, 13572, 13582, 13592, 13602,
        13610, 13621, 13631, 13638, 13553, 13641, 13580, 13406,  9686, 13711,
        13723, 13742, 13752, 10407, 13777, 10461, 13671,  9548],
       dtype=torch.int32)
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2],
        ...,
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2]], dtype=torch.int8)
tensor([[ 6111, 13760,  8486,  ...,     0,     0,     0],
        [13840,  6111, 13760,  ...,     0,     0,     0],
        [13678, 13848, 13792,  ...,     0,     0,     0],
        ...,
        [11511, 18873,  7109,  ...,     0,     0,     0],
        [18890, 18891, 18892,  ...,     0,     0,     0],
        [18781, 18785, 18908,  ...,     0,     0,     0]], dtype=torch.int32)
tensor([13657, 13844, 13854,  5872, 13884, 13889,  5555, 13700, 13859, 13930,
        13946,  3258, 13952, 13815,  8486, 13731, 13859,  9158,  6455, 14025,
        14046, 14046, 14053, 14066, 14042, 13963, 13781, 14104, 14111, 14120,
        14125, 14132, 14152, 14158, 13985,  5663, 14193, 14099, 14203, 14203,
        14099, 14318, 14306, 14397, 14359, 14485, 14502, 14654, 14663, 14698,
        14706, 14712,  2906, 14392, 14492, 14812, 14580, 14849, 14762, 14858,
        14648, 15052, 15108, 15147, 15176, 15222, 15303, 15381, 15418,  4124,
        15469, 15478, 15559, 15576, 15580, 15609, 15526, 15451,  4127, 15725,
        10758,  9850, 15776, 15612, 15879, 16062, 16117, 16140,  3771, 16216,
        16267, 16277, 16327, 15763, 16804, 16803, 16814, 17009,    98, 17059,
        17075, 17004, 17139, 17152, 17138, 17173, 17181, 17188, 17220, 17234,
        17261, 16845, 17278, 17300, 17318, 17341, 17158, 17375, 17395, 17403,
        17111, 17971, 18803, 18814, 18791, 18887, 18907, 18921],
       dtype=torch.int32)
tensor([13704, 13845, 13855, 13864, 13885, 13890, 13758, 13923, 13926,  6477,
        13947,  2120, 13953, 13933, 13657, 13972, 13829,  9633,  5986, 14038,
        14051, 14051, 14063,  3670, 14043, 13964, 14095, 13700, 13719, 13954,
        14126, 13672, 14153, 14159, 14182, 14186,  2459, 14093, 14203, 14201,
        14093, 14437, 14303, 14441, 14385,  2880, 14503, 14513, 14524, 14699,
        14707, 14713, 14397, 13034, 14809, 14813, 14836, 14850, 14347, 14858,
        14517, 15053, 15108, 15147, 15176, 15176, 15304, 15382, 15419, 15452,
        15470, 15479, 15560, 15346, 15327, 15610, 15527, 15666, 15458, 15726,
        15741,  9850,  8205, 15820, 15880, 16063, 16118, 16171, 16176, 15563,
        16268, 16064, 16322,  9850, 16805, 16804, 16811, 17005, 17020, 17060,
        17076, 17009, 17140, 17153, 17140, 17174, 17182, 17189, 17221, 17235,
        17262, 16774,  6205, 17301, 17319, 17004,   749, 17376, 17396, 17404,
        17076, 17972, 18804, 18815, 18871, 18888, 18780, 18922],
       dtype=torch.int32)
tensor([[0, 0, 1,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)
tensor([[18924, 18925, 18926,  ...,     0,     0,     0],
        [18943, 18944, 18945,  ...,     0,     0,     0],
        [18874, 18875, 18879,  ...,     0,     0,     0],
        ...,
        [18806, 18839, 18810,  ...,     0,     0,     0],
        [19040, 19176, 19369,  ...,     0,     0,     0],
        [18907, 18902, 18886,  ...,     0,     0,     0]], dtype=torch.int32)
tensor([18940, 18956, 18876, 18788, 18828, 18848, 18803, 18877, 19115, 18905,
        19010, 19122, 18947, 18927, 18785,  6007,  8428, 11448,  6737, 19173,
        19179,  4138, 19050, 19071, 19053, 19187, 18824, 18871, 19021, 19102,
          274, 19025, 18801, 18790, 18889, 18780, 18782,  6760, 19071, 18788,
        19108,   804, 19009, 18992, 18986, 19067, 19019,   553,  9404, 19053,
         6196, 19074, 19078,  5665, 18892, 19121, 18854, 18888, 19219,  5387,
        19238, 19016, 19075,   789,   804, 19005, 18996, 18991, 18982,  7817,
        18971,  6190, 18860, 18791, 18796, 18809, 19246, 19263,   804,  5592,
        16094, 19052, 19063,  6863,  6404,  8791, 18899,  5959, 18985, 19284,
        18890, 18904, 18883, 18781, 18896, 19299, 19309, 18784, 18876, 19114,
        19108, 18878, 18874, 18904, 18876,  6477, 19325,  5761, 19346, 18779,
        19347,  5724, 18962, 19349,  5633, 19083,  6411, 19022, 18839, 18860,
        19102, 18866, 19178,  6979, 13615, 19103, 18784, 19118],
       dtype=torch.int32)
tensor([18941, 18900, 18881, 18864, 18832, 18799, 18807, 18893, 19116, 18882,
        18878, 19139, 19151, 18910, 19114,  9301, 18961,  4138,  5858, 11450,
          877,  6383, 18967,  9404,  6196, 19188, 19100, 18819, 18856, 18839,
        11218, 18806, 18867, 18866, 18907, 18880, 18893, 19063, 19071, 18840,
        18905, 18974, 18977, 19196, 18789, 19077, 19050,   553, 19109, 19052,
        19019, 19060, 19068, 19057, 18889, 18886, 18829, 18881, 11748,  5951,
         6339, 19064, 19057, 18965, 18789,  5741,  1211,  6979, 18975, 19000,
        18994, 11972, 18808, 18849, 18811, 19100, 19247, 19264,   791, 18966,
        19071,   391, 19067, 19083,  5592, 19069, 18886, 19008,  7817, 19285,
        18893, 18781, 18895, 18880, 18891, 19300, 19310, 18904, 19137, 18886,
        18883, 19114, 18882, 18894, 19137,  7000, 19326, 19338, 19347,  3061,
        19344, 19334,  5422,  5846,  9606, 19237, 18779, 18853, 18870, 18823,
        18817, 18819, 19037,  6290, 18830, 18854, 18904, 18906],
       dtype=torch.int32)
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 2, 2, 2],
        ...,
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)
tensor([[18780, 18876, 18881,  ...,     0,     0,     0],
        [19374, 18954, 18918,  ...,     0,     0,     0],
        [16460,  5986,  6796,  ...,     0,     0,     0],
        ...,
        [ 7333, 22023, 22043,  ...,     0,     0,     0],
        [22083, 21995,     0,  ...,     0,     0,     0],
        [21979, 22086, 22046,  ...,     0,     0,     0]], dtype=torch.int32)
tensor([19144, 19380, 18886, 19108, 18896, 19132, 18937, 19411, 18908, 18885,
        18785, 18871, 18813, 18798, 18824, 19022, 19430, 19436, 18811, 18791,
         9856, 19086, 19191, 18831, 18810, 19022, 19021, 19137, 18900, 18903,
        18829, 18811, 18825,   877, 19073, 19081, 14003, 19047, 18886, 19120,
        18902, 18886, 18877, 18902, 18876, 19496, 14509, 19498, 14511, 14508,
          275, 19550, 18051,  5553,  6905, 19676, 19819, 19665, 11321, 20162,
        20171, 20204, 20319, 19794, 19797, 19907, 20275,  7706, 20110, 19875,
        20192,  6801, 20379, 20044, 19889,  6685,   888, 20489, 19740,  5861,
        19867, 19990, 20522, 15247,   796, 20538, 19835, 19704, 15605,  5714,
        20576, 19706, 20666, 21287, 21657, 21642, 21577, 21681, 21042, 21574,
         5896, 21991, 21989, 21991, 21992, 21990, 21998, 22006, 21982, 21987,
        21983, 21986, 21994, 21980, 21983, 22016, 22038,  5487, 21979, 21979,
        22010, 22039, 21997, 21980, 22019, 22050, 22058, 22089],
       dtype=torch.int32)
tensor([18932, 19381, 18889, 18902, 18908, 19387, 19395, 19412, 18898, 19118,
        18880, 18840, 18828, 18815, 18855, 13615, 19431, 15750, 18872, 18838,
         5880, 19096, 19439, 18819, 18825, 18870, 18847, 19108, 19118, 19121,
        18791, 18812, 18788, 19058, 19049, 19082,  8791,  5555, 18874, 18887,
        18897, 18874, 18906, 19137, 18900, 19486, 14511, 19498, 19502,   275,
        14510, 19551,   313,  6007,  7123, 20138, 19913, 15668, 20156, 20163,
        20169, 20162, 20053, 19770, 19615,  8337, 20274, 19868,  5982, 19866,
         8942,   825, 20447, 19883, 19889, 15826, 20447, 20489, 19740, 20176,
        19863, 20503, 20522, 14773, 19951, 20313, 19709, 19808, 19845, 20183,
        20447, 19884, 20672, 19014, 21318, 10316, 21665, 21400,  3204, 21548,
        21729, 21984, 21980, 21984, 21993, 21991, 21999, 22007, 21983, 21989,
        21990, 21995, 21995, 21981, 21990, 22014, 22015, 22060, 21987, 21978,
        21978, 22039, 22067, 21981, 22019, 19014, 22084, 22089],
       dtype=torch.int32)
tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)
tensor([[21979, 22091, 22043,  ...,     0,     0,     0],
        [22067, 22021, 22026,  ...,     0,     0,     0],
        [22043, 22044, 22107,  ...,     0,     0,     0],
        ...,
        [ 5954, 23326, 22949,  ...,     0,     0,     0],
        [22934,  6838,   227,  ...,     0,     0,     0],
        [19067,  6241, 23182,  ...,     0,     0,     0]], dtype=torch.int32)
tensor([ 5141, 22102, 22068, 22085, 22095, 22026, 22405, 22410, 22633, 22656,
        22672, 22688,   884,   848, 22728, 22834, 21611, 22989, 14375, 22716,
          890, 21374, 22453, 19074, 23144, 12992, 23073, 23155, 22764, 19587,
        19582,  6012, 13773, 23164, 23208,  6373, 22934, 22998, 23216,   652,
        23228, 23237,  1557, 23262, 23272,  5803,  5908, 23296, 19420, 13032,
        21611,   392, 22976, 13022, 17838, 22943, 18986, 23307, 11975,   864,
        23301,   859, 22819, 22880, 23319, 22452, 22441, 22892, 23305, 23304,
        22940, 22831, 22879, 10453, 14697, 23357, 23376, 17980, 23374, 23370,
        23382, 22617, 23382, 23378, 23383, 23374, 23422, 21441, 23444, 23458,
        23427, 23480, 23485, 13135, 22895, 22947,  5277, 22912, 22858, 22975,
        20993,   404,  6994, 18962, 11502, 18188, 23357,    69, 23274, 23700,
        21243, 22974, 23632,  6327, 22952, 23736, 21611,   859,  1227,  6737,
        23329, 22956, 22937, 22639, 22667, 23754, 22617, 23294],
       dtype=torch.int32)
tensor([22041, 22103, 22110, 22112, 22095, 22026, 16123, 22411, 22634, 22657,
        22673, 22689,   157, 19106, 22729, 22830, 17838, 22990, 22816,  9862,
        13773, 22485,  1220,  6119, 23143, 23149,   480, 23155, 22781, 19584,
        19591,  6012, 21611, 23165, 22821, 22503, 23210, 22507, 23217, 22513,
        23214, 23238,   866, 23263, 23273, 20742, 23293,  9433,  6473, 22737,
        22988,  5672, 22436, 22952, 22858,   574, 23203, 23308, 22863, 10114,
        22874, 23323, 22879, 22746, 14098, 23343, 23350, 17980, 22961, 22950,
        22946, 13702, 22812, 22972, 23394, 23378, 17828, 23382, 23373,  5925,
        23379, 17838, 10452, 23364, 20993,  5925, 23423, 23435, 23445, 23459,
        23471, 23481, 19063, 22942, 22900, 22876, 23183,   762, 22970, 22985,
        23659, 23667, 19697, 13455,  5586, 23676, 22440, 23240,   204, 23699,
        22836, 23317, 14375, 22996,  5954, 23317,  9810, 22878, 23699, 22895,
        13135, 23331, 22937, 22499, 13241, 22940, 22889, 23321],
       dtype=torch.int32)
tensor([[0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int8)

  0%|▍                                                                                                                                                                                                                                                                                                 | 6/3632 [00:04<48:25,  1.25it/s]